variables:
  app_id: 'pvr.rtradio'
  system.debug: true

trigger:
  branches:
    include:
    - Nexus
    - Omega
    - releases/*
  paths:
    include:
    - '*'
    exclude:
    - 'debian/*'

jobs:
  - job: Windows
    pool: My Pool

    strategy:
      matrix:
        Win32:
          GENERATOR: "Visual Studio 17 2022"
          ARCHITECTURE: Win32
          CONFIGURATION: Release
        Win64:
          GENERATOR: "Visual Studio 17 2022"
          ARCHITECTURE: x64
          CONFIGURATION: Release

    workspace:
      clean: all

    steps:
    - script: |
        cd .. 
        git clone --branch Omega --depth=1 https://github.com/xbmc/xbmc.git kodi
        cd $(Build.SourcesDirectory)
        mkdir build
        cd build
        mkdir "definition/$(app_id)"
        echo $(app_id) . . > definition/$(app_id)/$(app_id).txt
        mklink /J "$(Pipeline.Workspace)/$(app_id)" "$(Build.SourcesDirectory)"
      displayName: 'Prepare Repository'

    - script: |
        cmake -T host=x64 -G "$(GENERATOR)" -A $(ARCHITECTURE) $(WINSTORE) \
        -DADDONS_TO_BUILD=$(app_id) -DCMAKE_BUILD_TYPE=$(CONFIGURATION) \
        -DADDONS_DEFINITION_DIR=$(Pipeline.Workspace)/$(app_id)/build/definition \
        -DADDON_SRC_PREFIX=../.. -DCMAKE_INSTALL_PREFIX=../../kodi/addons \
        -DPACKAGE_ZIP=1 ../../kodi/cmake/addons
      displayName: 'Configure CMake'

    - script: |
        cmake --build . --config $(CONFIGURATION) --target $(app_id)
      displayName: 'Build Target'
